---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-zookeeper-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-zk-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-broker-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-broker-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-zookeeper-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-zk-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-broker-1
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-broker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-zookeeper-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-zk-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-broker-2
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/ubuntu/volume/tm-gla/kafka/kafka-broker-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeName: data-kafka-broker-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-1
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeName: data-kafka-broker-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-2
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeName: data-kafka-broker-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: data-kafka-zookeeper-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-1
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: data-kafka-zookeeper-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-2
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: data-kafka-zookeeper-2
